### ISSUE TITLE
Upload to a folder

### ISSUE THREAD

**Issue by janfeyen** [cloudinary/cloudinary_angular#116]
How could I change this upload example to upload to a specific folder?

**Comment by eitanp461** [comment]
@janfeyen You can add a `folder` attribute.
This is an optional folder name where the uploaded resource will be stored. The Public ID contains the full path of the uploaded resource, including the folder name.

Add it to the `form` like so:
```form.append('folder', 'angular_sample');```

Note that by default, when uploading via the API, folders are not automatically created in your Media Library. In order to automatically create the folders based on the API requests, please go to your account upload settings and set the 'Auto-create folders' option to enabled. 

You can find additional upload parameters [here ](https://cloudinary.com/documentation/image_upload_api_reference)

**Comment by eitanp461** [comment]
@janfeyen see full example of uploading to a folder here - https://github.com/cloudinary/cloudinary_angular/blob/master/samples/photo_album/app/js/photo-album/photo-upload.component.ts#L57

**Comment by eitanp461** [comment]
Answered and provided an example, closing due to time elapsed
