### ISSUE TITLE
Add funcionalities in the examples

### ISSUE THREAD

**Issue by netstart** [cloudinary/cloudinary_angular#127]
1 - Add signed Upload images

2 - Delete image using signed images, the actual code not work, if i add return_delete_token in the request, I receive: 
`X-Cld-Error:Return delete token parameter is not allowed when using unsigned upload. Only upload_preset,callback,public_id,folder,tags,context,face_coordinates,custom_coordinates upload parameters are allowed.`

3 - Replace existing image using the same public_id

**Comment by eitanp461** [comment]
@netstart the first 2 issues were answered [here](https://github.com/cloudinary/cloudinary_angular/issues/64#issuecomment-357510958).

As for replacing an existing image with the same public id, it is not supported for unsigned uploads by design, in order to restrict everybody from changing your uploaded assets without permission. 
You can find the documentation for the available upload parameters [here](https://cloudinary.com/documentation/image_upload_api_reference#upload)
