### ISSUE TITLE
Ability Skip SVG

### ISSUE THREAD

**Issue by chris480** [cloudinary/cloudinary_angular#305]
## Explain your use case
SVGs still get transformed and converted to some close format

## Describe the problem you’re trying to solve
Have the ability to cleanly and easily skip transformation of svgs if an file format is svg

## Do you have a proposed solution?
A new config at at?

**Comment by aksjoshi1** [comment]
@chris480 Can you provide more details on your workflow and what is happening and what you would like to happen?

**Comment by chris480** [comment]
@aksjoshi1 I have user generated content, and most of the time it's just jpgs or pngs. On occasion an svg is uploaded. Because I'm using transforms on the uploaded content, cloudinary will convert the svg to either jpg/png.

Ideally cloudinary could skip transforms of svgs without having write additional UI logic to determine if the image ID contains .svg

**Comment by eyalktCloudinary** [comment]
@chris480 If you're using upload presets in order to transform the images on upload, you can add local logic that checks the file's format, and chooses a different preset for SVG uploads (if you're using our [upload widget](https://cloudinary.com/documentation/upload_widget) you can do that with the help of the `preBatch` parameter (in order to check the file format) and the `prepare` parameter (in order to update the preset) - you can see an example [here](https://codepen.io/eyalkt/pen/gOLdEvO). Additional details regarding these parameters can be found [here](https://cloudinary.com/documentation/upload_widget_reference#advanced_parameters).

**Comment by eyalktCloudinary** [comment]
@chris480 Thanks for the additional details. We have an internal task for adding the option to retain SVG format when using f_auto (`fetch_format="auto"`). I'll update this thread about any progress made.
In addition, if you are on an enterprise plan, our Solutions team can fix this for your account - In that case, please open a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new).
