### ISSUE TITLE
Feature request: Video support

### ISSUE THREAD

**Issue by nadavivry** [cloudinary/cloudinary_angular#57]
It's great you guys created this module, but what about video support?

**Comment by roeeba** [comment]
It's on our road-map to support `cl-video` in our Angular SDK. There is currently no ETA we can share.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
Note the cl-video is supported- examples can be found on our sample project- https://github.com/cloudinary/cloudinary_angular/tree/master/samples/photo_album
