### ISSUE TITLE
@injectible causing errors, not needed for Cloudinary in cloudinary.service.

### ISSUE THREAD

**Issue by DennisSmolek** [cloudinary/cloudinary_angular#76]
In the `cloudinary.service` the `@injectable` works when you do plain dev/test builds but when you use the Angular-Cli it's throwing: 

```  javascript
ERROR in Can't resolve all parameters for Cloudinary in /path/to/src/lib/angular-cloudinary/cloudinary.service.ts: (?, ?)
```
`@injectable` is for injecting services into each other. This service though gets created from a factory with direct object references. In dev mode it simply ignores the issue but when you do `-prod` in the CLI it minifies and then eats this. 

Simply removing `@Injectible` resolves the problem. 

I'd submit a PR but I already have one out for the Angular 4 stuff and dont want to get that confused yet...

**Comment by eitanp461** [comment]
@DennisSmolek We have released cloudinary-core with a type definition file, see https://github.com/cloudinary/cloudinary_js/releases/tag/2.3.0.

I updated the Angular CLI sample with the --aot flag and it works now.
Please close this issue if it is fixed in your use case, or add more details to it for further analysis.

**Comment by DennisSmolek** [comment]
I don't have time to test but I'll close as you say it's working. When I get back next week I'll double check, Great work!
