### ISSUE TITLE
onload event

### ISSUE THREAD

**Issue by dottodot** [cloudinary/cloudinary_angular#81]
On the Angular (2/4) version is there any way to get an onload event from the img that's created. I've had a look through the src but can see anything that would suggest you can.

**Comment by eitanp461** [comment]
@dottodot 

We are [passing the attributes](https://github.com/cloudinary/cloudinary_angular/blob/angular_next/src/cloudinary-image.component.ts#L56) of `<cl-image>` to the underlying `<img>`, and expected `(load)="onLoad()"` or `on-load="onLoad()` to be passed to the `img` as well.

However Angular is not passing bindings as attributes to the underlying component, see [here](https://github.com/angular/angular/blob/08d86751b953c6ca20af4d03145281ef8f7141c0/packages/compiler/src/template_parser/template_parser.ts#L330).

A possible workaround is to use the native `onload` handler, however the drawback is that you can't reference your Angular component from the event handler since it is handled directly by the browser. Will that be sufficient for your use case?

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by bjornharvold** [comment]
This would be a great feature to have indeed. This use case has come up several times.
